name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Project
        run: pnpm run build

      - name: Prepare Static Files for GitHub Pages
        run: |
          mkdir -p ./gh-pages
          cp -r ./.next/static/* ./gh-pages/
          cp -r ./.next/server/pages/*.html ./gh-pages/
          mkdir -p ./gh-pages/_next/static
          cp -r ./.next/static/* ./gh-pages/_next/static/
          echo "Creating index.html if necessary"
          if [ -f ./gh-pages/404.html ]; then mv ./gh-pages/404.html ./gh-pages/index.html; fi

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
